---
title: "nbis-course-revealjs example"
subtitle: How to write a revealjs presentation
footer: NBIS course
author: John Doe
institute: NBIS
date: today
format:
  nbis-course-revealjs:
    nbishome:
      url: https://www.kth.se
      position:
        left: 130px
        bottom: 14px
    ultitle: true
    nbistitlelogo: true
revealjs-plugins:
  - nbishome
---

## Usage

This presentation uses the following document yaml header:

```yaml
---
title: "nbis-course-revealjs example"
subtitle: How to write a revealjs presentation
footer: NBIS course
author: John Doe
institute: NBIS
date: today
format: nbis-course-revealjs
---
```

## Home icon plugin

The extensions provides a home icon that by default is placed in the
bottom left corner of each slide, next to the menu. The exact position
can be configured via the `position` key. The home icon is a
customizable link that could point to, e.g., the course home page.

The plugin can be activated and customized by adding the following to
the document yaml header:

```yaml
format:
  nbis-course-revealjs:
    nbishome:
      url: https://nbis.se
      position:
        left: 100px
        bottom: 10px
revealjs-plugins:
  - nbishome
```

## Underlined titles

Various different title formats are supported. For instance, the
`ultitle` used here produces titles underlined with a green bar.

```yaml
format:
  nbis-course-revealjs:
    ultitle: true
```

## Title and slide logos

By default, a logo is added to the title page by making use of
`title-slide-attributes`. However, this prevent correct embedding of
resources. In order to generate slides with embedded resources, you
can set the `nbistitlelogo` key:

```yaml
format:
  nbis-course-revealjs:
    nbistitlelogo: false
```

If you want to omit the logo in the footer, you can unset the standard
`logo` key:

```yaml
format:
  nbis-course-revealjs:
    logo: ""
```

## Color customizations

Colors follow the [SciLifeLab visual identity
guidelines](https://www.scilifelab.se/community-pages/resources/visual-identity).
Theme colors are used to colorize elements, including:

- **strong**

- blockquotes

    > This is a quote

- code

```python
import numpy as np
```

- links: [nbis](https://nbis.se/)
